---

  - name: Install dependencies
    apt:
      name: {{ packages }}
      update_cache: yes
      state: present
      vars:
        packages:
        - cat "{{ apt_dep_path }}/{{ apt_dep_file }}"
